In [1]:
#Q1
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
#Q2
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [5]:
#Q3
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [6]:
#Q4
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [7]:
#Q5
df.groupby("origin")["fuel_efficiency_mpg"].max()["Asia"]

np.float64(41.2)

In [8]:
#Q6
df.horsepower.median()

np.float64(254.0)

In [9]:
modehorsepowervalue = df['horsepower'].mode()[0]
modehorsepowervalue

np.float64(252.0)

In [10]:
df['horsepower'].isnull().sum()

np.int64(877)

In [11]:
df.fillna(modehorsepowervalue, inplace=True)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,252.0,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,252.0,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [12]:
df['horsepower'].isnull().sum()

np.int64(0)

In [13]:
df.horsepower.median()

np.float64(252.0)

In [14]:
#Q7
asia_df = df[df["origin"] == "Asia"]
asia_df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [21]:
X = asia_df[['vehicle_weight', 'model_year']].iloc[:7,:]
X = X.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [22]:
XTX = X@X.T
XTX

array([[21961616, 22250432, 21921212, 22688888, 20753972, 24173916,
        22897924],
       [22250432, 22544164, 22209324, 22990376, 21022444, 24498332,
        23201348],
       [21921212, 22209324, 21880909, 22646666, 20716479, 24128437,
        22855443],
       [22688888, 22990376, 22646666, 23448884, 21428846, 24992538,
        23662582],
       [20753972, 21022444, 20716479, 21428846, 19630549, 22818647,
        21629633],
       [24173916, 24498332, 24128437, 24992538, 22818647, 26646941,
        25217899],
       [22897924, 23201348, 22855443, 23662582, 21629633, 25217899,
        23878861]])

In [23]:
XTX_inv = np.linalg.pinv(XTX)
XTX_inv

array([[ 4.38279333e-07,  6.97066123e-08,  4.95291129e-07,
        -5.87932998e-07,  1.90856231e-06, -1.69640601e-06,
        -3.11490552e-07],
       [ 6.97066123e-08,  1.17141786e-08,  7.86771771e-08,
        -9.17635542e-08,  3.01043872e-07, -2.66153687e-07,
        -4.82529561e-08],
       [ 4.95291129e-07,  7.86771771e-08,  5.59734047e-07,
        -6.64681393e-07,  2.15721691e-06, -1.91764036e-06,
        -3.52208541e-07],
       [-5.87932998e-07, -9.17635542e-08, -6.64681393e-07,
         7.93538112e-07, -2.56722053e-06,  2.28581234e-06,
         4.21433252e-07],
       [ 1.90856231e-06,  3.01043872e-07,  2.15721691e-06,
        -2.56722053e-06,  8.32116310e-06, -7.40187337e-06,
        -1.36158227e-06],
       [-1.69640601e-06, -2.66153687e-07, -1.91764036e-06,
         2.28581234e-06, -7.40187337e-06,  6.58737961e-06,
         1.21315592e-06],
       [-3.11490552e-07, -4.82529561e-08, -3.52208541e-07,
         4.21433252e-07, -1.36158227e-06,  1.21315592e-06,
         2.24025075e-07]])

In [24]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [25]:
XT = X.T
a = np.dot(XT, XTX_inv)
a

array([[-2.50082897e-04, -1.65786806e-05, -2.86196661e-04,
         3.99964853e-04, -1.18162927e-03,  1.10298508e-03,
         2.25354894e-04],
       [ 6.12974614e-04,  1.06954785e-04,  6.91249245e-04,
        -7.95968736e-04,  2.63152339e-03, -2.31749941e-03,
        -4.16221392e-04]])

In [26]:
w = np.dot(a, y)

In [27]:
sum(w)

np.float64(0.3691969690492639)